server:
  port: 8012

#================ Configuracion spring =================#
spring:
  application:
    name: regular-java-smartjob
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

#================ Configuracion JWT =================#
jwt:
  secret: 8Zl7W8Lg+3+mGNjWY6uTKCPAQqGs8QHdEKUAMuLWHQ0qhcA8L3+HN6iXwdIB9P3m8tFcDzvpDnBjtssACbK2MQ==
  expiration: 86400000 # 24h

#================ Configuracion Logging =================#
logging:
  level:
    root: INFO
    com.test.users.regular_java_smartjob: DEBUG
#================ Configuracion OpenAPI =================#
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /api-docs
    enabled: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
  info:
    title: API de Gesti贸n de Usuarios - Regular Java SmartJob
    version: 1.0.0
    description: API RESTful para la creaci贸n y gesti贸n de usuarios con autenticaci贸n JWT
    contact:
      name: Ferwis Anazco
      email: ferwis.89@gmail.com
      url: https://github.com/winsdeveloper/regular-java-smartjob-ferwis
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
